<?php

namespace App\Security\Permission;

final class TenantPermission
{

  public const ENTREPRISE_DOCUMENTS_MANAGE = 'ENTREPRISE_DOCUMENTS_MANAGE';
  public const DASHBOARD_ENTREPRISE_MANAGE = 'DASHBOARD_ENTREPRISE_MANAGE';
  public const CONVENTION_SIGNATURE_ENTREPRISE_MANAGE = 'CONVENTION_SIGNATURE_ENTREPRISE_MANAGE';

  public const ACCESS      = 'ENTITE_ACCESS';
  public const ADMIN       = 'ENTITE_ADMIN';
  public const FORMATEUR   = 'ENTITE_FORMATEUR';
  public const STAGIAIRE   = 'ENTITE_STAGIAIRE';
  public const ENTREPRISE  = 'ENTITE_ENTREPRISE';
  public const OF          = 'ENTITE_OF';
  public const OPCO        = 'ENTITE_OPCO';
  public const COMMERCIAL  = 'ENTITE_COMMERCIAL';




  public const FORMATEUR_EMARGEMENT_PDF_MANAGE = 'FORMATEUR_EMARGEMENT_PDF_MANAGE';

  public const FORMATEUR_DASHBOARD_MANAGE = 'FORMATEUR_DASHBOARD_MANAGE';
  public const FORMATEUR_EMARGEMENT_MANAGE = 'FORMATEUR_EMARGEMENT_MANAGE';
  public const FORMATEUR_ESPACE_MANAGE = 'FORMATEUR_ESPACE_MANAGE';
  public const FORMATEUR_SATISFACTION_MANAGE = 'FORMATEUR_SATISFACTION_MANAGE';
  public const FORMATEUR_POSITIONING_MANAGE = 'FORMATEUR_POSITIONING_MANAGE';
  public const FORMATEUR_RAPPORT_MANAGE = 'FORMATEUR_RAPPORT_MANAGE';



  public const STAGIAIRE_CONVENTION_SIGNATURE_MANAGE = 'STAGIAIRE_CONVENTION_SIGNATURE_MANAGE';
  public const STAGIAIRE_COURS_MANAGE = 'STAGIAIRE_COURS_MANAGE';
  public const STAGIAIRE_DASHBOARD_MANAGE = 'STAGIAIRE_DASHBOARD_MANAGE';
  public const STAGIAIRE_DOSSIER_INSCRIPTION_MANAGE = 'STAGIAIRE_DOSSIER_INSCRIPTION_MANAGE';
  public const STAGIAIRE_ELEARNING_MANAGE = 'STAGIAIRE_ELEARNING_MANAGE';
  public const STAGIAIRE_FORMATION_CONTENT_MANAGE = 'STAGIAIRE_FORMATION_CONTENT_MANAGE';
  public const STAGIAIRE_POSITIONING_MANAGE = 'STAGIAIRE_POSITIONING_MANAGE';
  public const STAGIAIRE_QCM_MANAGE = 'STAGIAIRE_QCM_MANAGE';
  public const STAGIAIRE_POSITIONING_LIST_MANAGE = 'STAGIAIRE_POSITIONING_LIST_MANAGE';
  public const STAGIAIRE_SATISFACTION_MANAGE = 'STAGIAIRE_SATISFACTION_MANAGE';
  public const STAGIAIRE_ESPACE_MANAGE = 'STAGIAIRE_ESPACE_MANAGE';
  public const STAGIAIRE_EMARGEMENT_MANAGE = 'STAGIAIRE_EMARGEMENT_MANAGE';











  public const FORMATION_CONTENT_MANAGE = 'FORMATION_CONTENT_MANAGE';
  public const SATISFACTION_MANAGE = 'SATISFACTION_MANAGE';
  public const CONTRAT_FORMATEUR_MANAGE = 'CONTRAT_FORMATEUR_MANAGE';
  public const DEPENSE_MANAGE = 'DEPENSE_MANAGE';
  public const QCM_ASSIGNMENT_MANAGE = 'QCM_ASSIGNMENT_MANAGE';
  public const FORMATEUR_SATISFACTION_ASSIGNMENT_MANAGE = 'FORMATEUR_SATISFACTION_ASSIGNMENT_MANAGE';
  public const FORMATEUR_MANAGE = 'FORMATEUR_MANAGE';
  public const FORMATEUR_SATISFACTION_ATTEMPT_MANAGE = 'FORMATEUR_SATISFACTION_ATTEMPT_MANAGE';
  public const FORMATEUR_SATISFACTION_TEMPLATE_MANAGE = 'FORMATEUR_SATISFACTION_TEMPLATE_MANAGE';
  public const TVA_API_MANAGE = 'TVA_API_MANAGE';
  public const SESSION_STAGIAIRE_MANAGE = 'SESSION_STAGIAIRE_MANAGE';
  public const QCM_ATTEMPT_MANAGE = 'QCM_ATTEMPT_MANAGE';
  public const QCM_MANAGE = 'QCM_MANAGE';
  public const QCM_FOLLOW_UP_MANAGE = 'QCM_FOLLOW_UP_MANAGE';
  public const RESERVATION_MANAGE = 'RESERVATION_MANAGE';
  public const SATISFACTION_ASSIGNMENT_MANAGE = 'SATISFACTION_ASSIGNMENT_MANAGE';
  public const SATISFACTION_ATTEMPT_MANAGE = 'SATISFACTION_ATTEMPT_MANAGE';
  public const SATISFACTION_STAGIAIRE_MANAGE = 'SATISFACTION_STAGIAIRE_MANAGE';
  public const SATISFACTION_RESULT_MANAGE = 'SATISFACTION_RESULT_MANAGE';
  public const SATISFACTION_TEMPLATE_MANAGE = 'SATISFACTION_TEMPLATE_MANAGE';
  public const SESSION_PIECE_MANAGE = 'SESSION_PIECE_MANAGE';
  public const SESSION_MANAGE = 'SESSION_MANAGE';
  public const SESSION_POSITION_MANAGE = 'SESSION_POSITION_MANAGE';
  public const SITE_MANAGE = 'SITE_MANAGE';
  public const TVA_DASHBOARD_MANAGE = 'TVA_DASHBOARD_MANAGE';
  public const TVA_DATATABLE_MANAGE = 'TVA_DATATABLE_MANAGE';
  public const UTILISATEUR_MANAGE = 'UTILISATEUR_MANAGE';
  public const UTILISATEUR_DEVIS_MANAGE = 'UTILISATEUR_DEVIS_MANAGE';
  public const UTILISATEUR_EMAIL_MANAGE = 'UTILISATEUR_EMAIL_MANAGE';
  public const UTILISATEUR_FACTURE_MANAGE = 'UTILISATEUR_FACTURE_MANAGE';
  public const FORMATION_CONTENT_REORDER_MANAGE = 'FORMATION_CONTENT_REORDER_MANAGE';
  public const FORMATION_MANAGE = 'FORMATION_MANAGE';
  public const INSCRIPTION_MANAGE = 'INSCRIPTION_MANAGE';
  public const OCR_MANAGE = 'OCR_MANAGE';
  public const PAIEMENT_MANAGE = 'PAIEMENT_MANAGE';
  public const PASSEPORT_PREVENTION_MANAGE = 'PASSEPORT_PREVENTION_MANAGE';
  public const PLANNING_FORMATEUR_MANAGE = 'PLANNING_FORMATEUR_MANAGE';
  public const PLANNING_SESSION_MANAGE = 'PLANNING_SESSION_MANAGE';
  public const PLANNING_STAGIAIRES_MANAGE = 'PLANNING_STAGIAIRES_MANAGE';
  public const POSITIONING_ASSIGNMENT_MANAGE = 'POSITIONING_ASSIGNMENT_MANAGE';
  public const POSITIONING_CHAPTER_MANAGE = 'POSITIONING_CHAPTER_MANAGE';
  public const POSITIONING_MANAGE = 'POSITIONING_MANAGE';
  public const POSITIONING_ITEM_MANAGE = 'POSITIONING_ITEM_MANAGE';
  public const POSITIONING_QUESTIONNAIRE_MANAGE = 'POSITIONING_QUESTIONNAIRE_MANAGE';
  public const PROSPECT_MANAGE = 'PROSPECT_MANAGE';
  public const PROSPECT_DEVIS_MANAGE = 'PROSPECT_DEVIS_MANAGE';
  public const PROSPECT_EMAIL_MANAGE = 'PROSPECT_EMAIL_MANAGE';
  public const PROSPECT_INTERACTION_MANAGE = 'PROSPECT_INTERACTION_MANAGE';
  public const ENTREPRISE_MANAGE = 'ENTREPRISE_MANAGE';
  public const EMAIL_TEMPLATE_MANAGE = 'EMAIL_TEMPLATE_MANAGE';
  public const ENGIN_MANAGE = 'ENGIN_MANAGE';
  public const ENTITE_PREFERENCE_MANAGE = 'ENTITE_PREFERENCE_MANAGE';
  public const FINANCE_DASHBOARD_MANAGE = 'FINANCE_DASHBOARD_MANAGE';
  public const FINANCE_DATATABLE_MANAGE = 'FINANCE_DATATABLE_MANAGE';
  public const CONVENTION_MANAGE = 'CONVENTION_MANAGE';
  public const DEVIS_MANAGE = 'DEVIS_MANAGE';
  public const DOCUMENT_PDF_MANAGE = 'DOCUMENT_PDF_MANAGE';
  public const DOSSIER_INSCRIPTION_MANAGE = 'DOSSIER_INSCRIPTION_MANAGE';
  public const ELEARNING_CONTENT_MANAGE = 'ELEARNING_CONTENT_MANAGE';
  public const ELEARNING_CONTENT_REORDER_MANAGE = 'ELEARNING_CONTENT_REORDER_MANAGE';
  public const ELEARNING_COURSE_MANAGE = 'ELEARNING_COURSE_MANAGE';
  public const ELEARNING_ENROLLMENT_MANAGE = 'ELEARNING_ENROLLMENT_MANAGE';
  public const BPF_MANAGE = 'BPF_MANAGE';
  public const CATEGORIE_MANAGE = 'CATEGORIE_MANAGE';
  public const CHARGE_MANAGE = 'CHARGE_MANAGE';

  public const ADMIN_DASHBOARD_MANAGE = 'ENTITE_ADMIN_DASHBOARD_MANAGE';
  public const AVOIR_MANAGE = 'ENTITE_AVOIR_MANAGE';
  public const FACTURE_MANAGE = 'ENTITE_FACTURE_MANAGE';
  public const ATTESTATION_MANAGE = 'ENTITE_ATTESTATION_MANAGE';
  public const USERS_MANAGE = 'ENTITE_USERS_MANAGE';
  public const BILLING_MANAGE = 'ENTITE_BILLING_MANAGE';

  /**
   * ✅ Liste exhaustive des permissions "tenant" gérées par TenantVoter.
   * Utilise ça dans supports():
   *   return $subject instanceof Entite && in_array($attribute, TenantPermission::ALL, true);
   */
  public const ALL = [
    self::ENTREPRISE_DOCUMENTS_MANAGE,
    self::DASHBOARD_ENTREPRISE_MANAGE,
    self::CONVENTION_SIGNATURE_ENTREPRISE_MANAGE,

    self::ACCESS,
    self::ADMIN,
    self::FORMATEUR,
    self::STAGIAIRE,
    self::ENTREPRISE,
    self::OF,
    self::OPCO,
    self::COMMERCIAL,

    self::FORMATEUR_EMARGEMENT_PDF_MANAGE,
    self::FORMATEUR_DASHBOARD_MANAGE,
    self::FORMATEUR_EMARGEMENT_MANAGE,
    self::FORMATEUR_ESPACE_MANAGE,
    self::FORMATEUR_SATISFACTION_MANAGE,
    self::FORMATEUR_POSITIONING_MANAGE,
    self::FORMATEUR_RAPPORT_MANAGE,
    self::STAGIAIRE_CONVENTION_SIGNATURE_MANAGE,
    self::STAGIAIRE_COURS_MANAGE,
    self::STAGIAIRE_DASHBOARD_MANAGE,
    self::STAGIAIRE_DOSSIER_INSCRIPTION_MANAGE,
    self::STAGIAIRE_ELEARNING_MANAGE,
    self::STAGIAIRE_POSITIONING_MANAGE,
    self::STAGIAIRE_QCM_MANAGE,
    self::STAGIAIRE_POSITIONING_LIST_MANAGE,
    self::STAGIAIRE_SATISFACTION_MANAGE,
    self::STAGIAIRE_ESPACE_MANAGE,
    self::STAGIAIRE_EMARGEMENT_MANAGE,
    self::CONTRAT_FORMATEUR_MANAGE,
    self::DEPENSE_MANAGE,
    self::QCM_ASSIGNMENT_MANAGE,
    self::FORMATEUR_SATISFACTION_ASSIGNMENT_MANAGE,
    self::FORMATEUR_MANAGE,
    self::FORMATEUR_SATISFACTION_ATTEMPT_MANAGE,
    self::FORMATEUR_SATISFACTION_TEMPLATE_MANAGE,
    self::STAGIAIRE_FORMATION_CONTENT_MANAGE,
    self::FORMATION_CONTENT_MANAGE,
    self::TVA_API_MANAGE,
    self::SESSION_STAGIAIRE_MANAGE,
    self::QCM_ATTEMPT_MANAGE,
    self::QCM_MANAGE,
    self::SATISFACTION_MANAGE,
    self::QCM_FOLLOW_UP_MANAGE,
    self::RESERVATION_MANAGE,
    self::SATISFACTION_ASSIGNMENT_MANAGE,
    self::SATISFACTION_ATTEMPT_MANAGE,
    self::SATISFACTION_STAGIAIRE_MANAGE,
    self::SATISFACTION_RESULT_MANAGE,
    self::SATISFACTION_TEMPLATE_MANAGE,
    self::SESSION_PIECE_MANAGE,
    self::SESSION_MANAGE,
    self::SESSION_POSITION_MANAGE,
    self::SITE_MANAGE,
    self::TVA_DASHBOARD_MANAGE,
    self::TVA_DATATABLE_MANAGE,
    self::UTILISATEUR_MANAGE,
    self::UTILISATEUR_DEVIS_MANAGE,
    self::UTILISATEUR_EMAIL_MANAGE,
    self::UTILISATEUR_FACTURE_MANAGE,
    self::FORMATION_CONTENT_REORDER_MANAGE,
    self::FORMATION_MANAGE,
    self::INSCRIPTION_MANAGE,
    self::OCR_MANAGE,
    self::PAIEMENT_MANAGE,
    self::PASSEPORT_PREVENTION_MANAGE,
    self::PLANNING_FORMATEUR_MANAGE,
    self::PLANNING_SESSION_MANAGE,
    self::PLANNING_STAGIAIRES_MANAGE,
    self::POSITIONING_ASSIGNMENT_MANAGE,
    self::POSITIONING_CHAPTER_MANAGE,
    self::POSITIONING_MANAGE,
    self::POSITIONING_ITEM_MANAGE,
    self::POSITIONING_QUESTIONNAIRE_MANAGE,
    self::PROSPECT_MANAGE,
    self::PROSPECT_DEVIS_MANAGE,
    self::PROSPECT_EMAIL_MANAGE,
    self::PROSPECT_INTERACTION_MANAGE,
    self::ENTREPRISE_MANAGE,
    self::EMAIL_TEMPLATE_MANAGE,
    self::ENGIN_MANAGE,
    self::ENTITE_PREFERENCE_MANAGE,
    self::FINANCE_DASHBOARD_MANAGE,
    self::FINANCE_DATATABLE_MANAGE,
    self::CONVENTION_MANAGE,
    self::DEVIS_MANAGE,
    self::DOCUMENT_PDF_MANAGE,
    self::DOSSIER_INSCRIPTION_MANAGE,
    self::ELEARNING_CONTENT_MANAGE,
    self::ELEARNING_CONTENT_REORDER_MANAGE,
    self::ELEARNING_COURSE_MANAGE,
    self::ELEARNING_ENROLLMENT_MANAGE,
    self::BPF_MANAGE,
    self::CATEGORIE_MANAGE,
    self::CHARGE_MANAGE,

    self::ADMIN_DASHBOARD_MANAGE,
    self::AVOIR_MANAGE,
    self::FACTURE_MANAGE,
    self::ATTESTATION_MANAGE,
    self::USERS_MANAGE,
    self::BILLING_MANAGE,
  ];
}
