# config/packages/liip_imagine.yaml
liip_imagine:
  resolvers:
    default:
      web_path: ~

  twig:
    mode: lazy

  filter_sets:
    cache: ~

    cover_small:
      quality: 80
      filters:
        thumbnail: { size: [360, 240], mode: outbound }

    gallery_large:
      quality: 82
      filters:
        thumbnail: { size: [1600, 900], mode: outbound }
