framework:
    rate_limiter:
        two_factor_send:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
        two_factor_verify:
            policy: sliding_window
            limit: 10
            interval: '15 minutes'
