# config/routes.yaml
redirect_root_to_fr:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /fr/
    permanent: false

home_locale:
  path:
    fr: /fr/
    en: /en/
  controller: App\Controller\Public\PublicController::index

_default:
  resource: ../src/Controller/
  type: attribute
  prefix:
    fr: "/fr"
    en: "/en"
